### ISSUE TITLE
Exceptions thrown in async methods get lost

### ISSUE THREAD

**Issue by chausner** [ttrider/PowerShellAsync#1]
Thank you for this great little library. It seems to work well apart from the fact that any exceptions that my cmdlets throw simply disappear. I propose that the behavior should be as close as possible to exceptions in synchronous cmdlets, i.e. exceptions should stop the pipeline and get printed out on the console.

Exceptions thrown in async code get wrapped in an AggregateException which is not very useful when printed on the console. Ideally, your library would unwrap these before rethrowing them, at least for the common case when there's only one inner exception.

**Comment by tig** [comment]
Thomas, why'd you close this? I think this is still an issue.

**Comment by ttrider** [comment]
Probably by mistake.

BTW, would you like to take over this project? I simply has no means to continue it…

**Comment by tig** [comment]
Actually, I think I was wrong. I am seeing exceptions as expected. 

For now leave it closed.

I'm not going to volunteer to take it over just yet. I'm not smart enough to understand how it actually works. I'll let you know if I change my mind.
