### ISSUE TITLE
Task continuations do not resume on main "Pipeline Execution" thread 

### ISSUE THREAD

**Issue by pgrefviau** [ttrider/PowerShellAsync#2]
I ran into exceptions thrown by System.Management.Automation methods when trying to invoke script snippets from within the ProcessRecordAsync override of an AsyncCmdlet. More specifically, the exception originated from the [System.Management.Automation.ScriptBlock.GetContextFromTLS()](https://github.com/PowerShell/PowerShell/blob/02b5f357a20e6dee9f8e60e3adb9025be3c94490/src/System.Management.Automation/engine/hostifaces/PowerShell.cs#L3615) method. `LocalPipeline.GetExecutionContextFromTLS()` would always return `null` for some reason. 

After some investigation, I realized that that, earlier in my Cmdlet's control flow, an async call was made whose continuation did not marshall back to the initial thread (appropriately called "Pipeline Execution Thread"), which led to the "CommandInvokedFromWrongThread" error. 

The AsyncCmdlet logic should ensure that the tasks awaited from within the various 'async' method overload it exposes are marshalled back to that main thread specifically to avoid running into those issues.

**Comment by tig** [comment]
shouldn't this issue be closed?
