### ISSUE TITLE
Support .NET Core 3.1?

### ISSUE THREAD

**Issue by tig** [ttrider/PowerShellAsync#5]
Please. Thanks.

**Comment by ttrider** [comment]
I'll do my best. Its been over 3 years since I touched .NET. 
Let me see if I can find a Windows box with dev environment to convert the project.

Thank You,

Vladimir

**Comment by tig** [comment]
I think i'm close to having it working. I'll do a PR...

**Comment by tig** [comment]
Yep. Got it working. Had to ditch the jetbrains.annotations stuff tho.

**Comment by ttrider** [comment]
Hello Charlie,

Thank You for taking care of this change!
I'll be happy to merge and publish your updates :)

Vladimir
